
SOURCES := \
	nodePattern.ml \
	build.ml \
	partition.ml \
	ruleContext.ml \
	dataType.ml \
        outputBroker.ml \
	userRule.ml \
	

RESULT := twbseq
PACKS := twb.core twb.types extlib

all: ncl

include $(OCAMLMAKEFILE)
