
SOURCES := \
	sbl.ml \
	nodePattern.ml \
	build.ml \
	partition.ml \
	ruleContext.ml \
	userData.ml \
	datatype.ml \
	outputBroker.ml \
	userRule.ml \
	
#	userStrategy.ml

RESULT := twbseq
PACKS := twb.core twb.types

all: ncl

include $(OCAMLMAKEFILE)
